version: '3'

services:
  product-service:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
  
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service